
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Denna sida visar information om hur mycket poäng varje elevhem har.
 *
 * @author Elinore Hagman
 */
public class Elevhemspokal_elev extends javax.swing.JFrame {

    private InfDB idb;

    // Creates new form Elevhemspokal_elev
    public Elevhemspokal_elev(InfDB idb) {
        initComponents();
        this.idb = idb;

        // Dessa metoder anropas när sidan öppnas och fyller i poängen för elevhemmen och visar det ledande elevhemmet.
        fyllIPoang();
        VisaLedandeElevhem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbGryffindor = new javax.swing.JLabel();
        lbSlytherin = new javax.swing.JLabel();
        lbRavenclaw = new javax.swing.JLabel();
        lbHufflepuff = new javax.swing.JLabel();
        iconPokalH = new javax.swing.JLabel();
        iconPokalR = new javax.swing.JLabel();
        iconPokalS = new javax.swing.JLabel();
        iconPokalG = new javax.swing.JLabel();
        lbPoangG = new javax.swing.JLabel();
        lbPoangS = new javax.swing.JLabel();
        lbPoangH = new javax.swing.JLabel();
        lbPoangR = new javax.swing.JLabel();
        panelTitel = new javax.swing.JPanel();
        lbRubrik = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbGryffindor.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbGryffindor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbGryffindor.setText("Gryffindor");

        lbSlytherin.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbSlytherin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSlytherin.setText("Slytherin");

        lbRavenclaw.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbRavenclaw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRavenclaw.setText("Ravenclaw");

        lbHufflepuff.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbHufflepuff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHufflepuff.setText("Hufflepuff");

        iconPokalH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_huf.png"))); // NOI18N

        iconPokalR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_raw.png"))); // NOI18N

        iconPokalS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_slyt.png"))); // NOI18N

        iconPokalG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_gryf.png"))); // NOI18N

        lbPoangG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPoangG.setText("PoängG");

        lbPoangS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPoangS.setText("PoängS");

        lbPoangH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPoangH.setText("PoängH");

        lbPoangR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPoangR.setText("PoängR");

        panelTitel.setBackground(new java.awt.Color(204, 204, 204));

        lbRubrik.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lbRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRubrik.setText("Elevhemspoäng");

        javax.swing.GroupLayout panelTitelLayout = new javax.swing.GroupLayout(panelTitel);
        panelTitel.setLayout(panelTitelLayout);
        panelTitelLayout.setHorizontalGroup(
            panelTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTitelLayout.setVerticalGroup(
            panelTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbRubrik)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnTillbaka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8-go-back-24.png"))); // NOI18N
        btnTillbaka.setText("Gå tillbaka");
        btnTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTillbakaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbGryffindor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconPokalG)
                        .addComponent(lbPoangG, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconPokalS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPoangS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbSlytherin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbHufflepuff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(iconPokalH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPoangH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconPokalR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPoangR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbRavenclaw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTillbaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPoangG)
                    .addComponent(lbPoangS)
                    .addComponent(lbPoangH)
                    .addComponent(lbPoangR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconPokalR)
                    .addComponent(iconPokalH)
                    .addComponent(iconPokalS)
                    .addComponent(iconPokalG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSlytherin)
                    .addComponent(lbGryffindor)
                    .addComponent(lbHufflepuff)
                    .addComponent(lbRavenclaw))
                .addGap(70, 70, 70)
                .addComponent(btnTillbaka)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTillbakaMouseClicked
    // Stänger denna sida och går tillbaka till huvudsidan för elever.
    
        setVisible(false);
        Huvudsida_elev elevsidan = new Huvudsida_elev(idb);
        elevsidan.setVisible(true);
    }//GEN-LAST:event_btnTillbakaMouseClicked

    private void fyllIPoang() {
    // Denna metod fyller ut poängen för elevhemmen ovanför pokalerna.

        try {
            String gryffindorPoang = idb.fetchSingle("select HUSPOANG from ELEVHEM where ELEVHEMSNAMN='Gryffindor'");
            String SlytherinPoang = idb.fetchSingle("select HUSPOANG from ELEVHEM where ELEVHEMSNAMN='Slytherin'");
            String HufflepuffPoang = idb.fetchSingle("select HUSPOANG from ELEVHEM where ELEVHEMSNAMN='Hufflepuff'");
            String ravenclawPoang = idb.fetchSingle("select HUSPOANG from ELEVHEM where ELEVHEMSNAMN='Ravenclaw'");

            lbPoangG.setText(gryffindorPoang);
            lbPoangS.setText(SlytherinPoang);
            lbPoangH.setText(HufflepuffPoang);
            lbPoangR.setText(ravenclawPoang);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Sökningen gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }

    private void VisaLedandeElevhem() {
    // Visar vilket elevhem det är som leder genom att uppdatera pokalbilden elevhemmet i fråga har.

        try {
            String ledandePoang = idb.fetchSingle("SELECT MAX(HUSPOANG) FROM ELEVHEM");
            String ledandeElevhem = idb.fetchSingle("SELECT ELEVHEMSNAMN FROM ELEVHEM WHERE HUSPOANG = " + ledandePoang);

            if (ledandeElevhem.equals("Gryffindor")) {
                iconPokalG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_gryfw.png")));
                
            } else if (ledandeElevhem.equals("Slytherin")) {
                iconPokalS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_slytw.png")));
                
            } else if (ledandeElevhem.equals("Hufflepuff")) {
                iconPokalH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_hufw.png")));
                
            } else if (ledandeElevhem.equals("Ravenclaw")) {
                iconPokalR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/pokal_raww.png")));
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Sökningen gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnTillbaka;
    private javax.swing.JLabel iconPokalG;
    private javax.swing.JLabel iconPokalH;
    private javax.swing.JLabel iconPokalR;
    private javax.swing.JLabel iconPokalS;
    private javax.swing.JLabel lbGryffindor;
    private javax.swing.JLabel lbHufflepuff;
    private javax.swing.JLabel lbPoangG;
    private javax.swing.JLabel lbPoangH;
    private javax.swing.JLabel lbPoangR;
    private javax.swing.JLabel lbPoangS;
    private javax.swing.JLabel lbRavenclaw;
    private javax.swing.JLabel lbRubrik;
    private javax.swing.JLabel lbSlytherin;
    private javax.swing.JPanel panelTitel;
    // End of variables declaration//GEN-END:variables
}
