
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Denna sida hanterar elevinformation och användaren kan registrera nya, ändra redan existerande
 * elevers information, eller bara kolla upp information. Användaren kan även ta bort elever.
 *
 * @author Elinore Hagman
 */
public class Elever_admin extends javax.swing.JFrame {

    private InfDB idb;

    // Creates new form Elever_admin
    public Elever_admin(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitel = new javax.swing.JPanel();
        lbRubrik = new javax.swing.JLabel();
        iconElever = new javax.swing.JLabel();
        lbValjElev = new javax.swing.JLabel();
        txtSok = new javax.swing.JTextField();
        lbElevId = new javax.swing.JLabel();
        lbFornamn = new javax.swing.JLabel();
        lbEfternamn = new javax.swing.JLabel();
        txtElevId = new javax.swing.JTextField();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        lbSubRubrik = new javax.swing.JLabel();
        btnRegistrera = new javax.swing.JButton();
        btnAndra = new javax.swing.JButton();
        lbElevhem = new javax.swing.JLabel();
        lbSovsal = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JLabel();
        btnTomFalt = new javax.swing.JButton();
        btnSok = new javax.swing.JButton();
        txtTips = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        btnPrefekt = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        elevLista = new javax.swing.JTextArea();
        cbElevhem = new javax.swing.JComboBox<>();
        cbSovsal = new javax.swing.JComboBox<>();
        btnUppdateradLista = new javax.swing.JButton();
        lbInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTitel.setBackground(new java.awt.Color(204, 204, 204));

        lbRubrik.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        lbRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbRubrik.setText("Hantera elever");

        iconElever.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8-graduate-filled-50.png"))); // NOI18N

        javax.swing.GroupLayout panelTitelLayout = new javax.swing.GroupLayout(panelTitel);
        panelTitel.setLayout(panelTitelLayout);
        panelTitelLayout.setHorizontalGroup(
            panelTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(iconElever)
                .addGap(18, 18, 18)
                .addComponent(lbRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitelLayout.setVerticalGroup(
            panelTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitelLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(panelTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconElever, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        lbValjElev.setText("Välj elev:");

        txtSok.setText("Förnamn och efternamn..");
        txtSok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSokMouseClicked(evt);
            }
        });

        lbElevId.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbElevId.setText("Elev ID:");

        lbFornamn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbFornamn.setText("Förnamn:");

        lbEfternamn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbEfternamn.setText("Efternamn:");

        txtElevId.setEditable(false);

        lbSubRubrik.setFont(new java.awt.Font("Lucida Grande", 2, 14)); // NOI18N
        lbSubRubrik.setText("Välj elev och ändra sedan nedanför");

        btnRegistrera.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        btnRegistrera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8-chevron-right-24.png"))); // NOI18N
        btnRegistrera.setText("Registrera ny elev");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        lbElevhem.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbElevhem.setText("Elevhem:");

        lbSovsal.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lbSovsal.setText("Sovsal:");

        btnTillbaka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8-go-back-24.png"))); // NOI18N
        btnTillbaka.setText("Gå tillbaka");
        btnTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTillbakaMouseClicked(evt);
            }
        });

        btnTomFalt.setText("Töm fält");
        btnTomFalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomFaltActionPerformed(evt);
            }
        });

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        txtTips.setText(" ");

        btnTaBort.setBackground(new java.awt.Color(251, 220, 188));
        btnTaBort.setText("Ta bort elev");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnPrefekt.setText("Prefekt");

        elevLista.setEditable(false);
        elevLista.setColumns(20);
        elevLista.setRows(5);
        jScrollPane2.setViewportView(elevLista);

        cbElevhem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbElevhemItemStateChanged(evt);
            }
        });

        btnUppdateradLista.setText("Visa uppdaterad elevlista");
        btnUppdateradLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateradListaActionPerformed(evt);
            }
        });

        lbInfo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lbInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbInfo.setText("Om det finns många elever på skolan kan det ta en stund att ladda fram listan.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSubRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbElevId)
                                            .addComponent(lbElevhem)
                                            .addComponent(lbFornamn))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbEfternamn)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFornamn)
                                    .addComponent(txtElevId, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txtEfternamn, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(btnPrefekt)
                                    .addComponent(cbElevhem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAndra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSovsal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnTomFalt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbSovsal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(58, 58, 58))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTillbaka)))
                .addGap(19, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbValjElev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSok, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSok, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistrera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUppdateradLista))
                    .addComponent(txtTips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addComponent(panelTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTips)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbValjElev)
                    .addComponent(txtSok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSubRubrik)
                    .addComponent(btnSok))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnRegistrera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUppdateradLista))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbElevId)
                            .addComponent(txtElevId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbFornamn)
                            .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbEfternamn)
                            .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrefekt)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbElevhem)
                            .addComponent(cbElevhem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSovsal)
                            .addComponent(cbSovsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAndra)
                            .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTomFalt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(btnTillbaka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
        // Anropar registreringssidan där en kan lägga till elever på Hogwarts.
        LaggTillElev registrerasidan = new LaggTillElev(idb);
        registrerasidan.setVisible(true);
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void fyllElevhemCombobox() {
    // Denna metod fyller ut dropdown-menyn med de olika elevhemmen som finns i databasen.

        try {
            ArrayList<HashMap<String, String>> elevhemLista = idb.fetchRows("SELECT ELEVHEMSNAMN FROM ELEVHEM");

            // For-loopen går igenom varje namn som finns i kolumnen ELEVHEMSNAMN och lägger till den i dropdown-menyn.
            for (int i = 0; i < elevhemLista.size(); i++) {
                cbElevhem.addItem(elevhemLista.get(i).get("ELEVHEMSNAMN"));
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }

    private void fyllListan() {
        // Metoden fyller listan med alla elever som går på Hogwarts.

        // Detta tar bort det som finns i högra textfältet och gör så inte textfältet som visar listan upprepar flera listor på varandra.
        elevLista.setText("");

        try {
            ArrayList<String> fornamnLista = idb.fetchColumn("SELECT FORNAMN FROM ELEV ORDER BY SOVSAL, EFTERNAMN ASC");
            ArrayList<String> efternamnLista = idb.fetchColumn("SELECT EFTERNAMN FROM ELEV ORDER BY SOVSAL, EFTERNAMN ASC");
            ArrayList<String> sovsalLista = idb.fetchColumn("SELECT SOVSAL FROM ELEV ORDER BY SOVSAL, EFTERNAMN ASC");

            // Loopen går igenom alla namn och lägger till förnamn, efternamn, elevhem och sovsal i listan.
            for (int i = 0; i < fornamnLista.size(); i++) {

                String elevhem = idb.fetchSingle("SELECT ELEVHEMSNAMN FROM ELEVHEM JOIN SOVSAL ON ELEVHEM_ID = SOVSAL.ELEVHEM JOIN ELEV ON SOVSAL_ID = ELEV.SOVSAL WHERE ELEV.FORNAMN = '" + fornamnLista.get(i) + "'");

                String elevId = idb.fetchSingle("SELECT ELEV_ID FROM ELEV WHERE FORNAMN = '" + fornamnLista.get(i) + "' AND EFTERNAMN = '" + efternamnLista.get(i) + "'");
                int elevIdInt = Integer.parseInt(elevId);

                // Kollar om eleverna var för sig är representerade som prefekt i elevhemmet ifråga.
                String prefektstatus = idb.fetchSingle("SELECT PREFEKT FROM ELEVHEM JOIN SOVSAL ON ELEVHEM_ID = SOVSAL.ELEVHEM JOIN ELEV ON SOVSAL_ID = ELEV.SOVSAL WHERE PREFEKT = " + elevIdInt);

                // Om eleven är prefekt kommer en extra rad skrivas in bredvid namnet på eleven ifråga.
                if (prefektstatus != null) {
                    elevLista.append("Namn: " + fornamnLista.get(i) + " " + efternamnLista.get(i) + " *PREFEKT*\nElevhem: " + elevhem + "\nSovsal: " + sovsalLista.get(i) + "\n\n");

                    // Om eleven inte är prefekt kommer ordet *prefekt* inte skrivas med i den enskilde elevens information.
                } else {
                    elevLista.append("Namn: " + fornamnLista.get(i) + " " + efternamnLista.get(i) + "\nElevhem: " + elevhem + "\nSovsal: " + sovsalLista.get(i) + "\n\n");
                }
            }

            // Detta gör att startpositionen i listan är i toppen av textfältet.
            elevLista.setSelectionStart(0);
            elevLista.setSelectionEnd(0);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel med listan!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
    // Denna metod ändrar den information användaren har skrivit i fältet till vänster när den klickar på "Ändra".

            String elevId = txtElevId.getText();
            String fornamn = txtFornamn.getText();
            String efternamn = txtEfternamn.getText();
            String sovsal = cbSovsal.getSelectedItem().toString();
            String elevhem = cbElevhem.getSelectedItem().toString();
            boolean prefektstatus = btnPrefekt.isSelected();

            try {

                // Dessa ser till att textfälten inte är tomma, och inte fler än ett namn har skrivits in när användaren försöker ändra elevinformation.
                if (Validering.Kolla3TommaFalt(txtSok, txtFornamn, txtFornamn)) {
                    if (Validering.KollaOmEndastEttNamn(txtFornamn, txtEfternamn)) {

                        idb.update("UPDATE ELEV SET FORNAMN = '" + fornamn + "' WHERE ELEV_ID =" + elevId);
                        idb.update("UPDATE ELEV SET EFTERNAMN = '" + efternamn + "' WHERE ELEV_ID =" + elevId);
                        idb.update("UPDATE ELEV SET SOVSAL = '" + sovsal + "' WHERE ELEV_ID =" + elevId);

                        // Kollar om eleven användaren valt är prefekt i nuläget.
                        String prefektKontroll = idb.fetchSingle("SELECT ELEV_ID FROM ELEV JOIN SOVSAL ON ELEV.SOVSAL = SOVSAL_ID JOIN ELEVHEM ON ELEVHEM_ID = SOVSAL.ELEVHEM WHERE PREFEKT = " + elevId);
                        
                        // Kollar om användaren fyllt i knappen för prefektstatus och om den är ifylld ändras prefekten till denna elev.
                        if (prefektstatus == true ) {
                            idb.update("UPDATE ELEVHEM SET PREFEKT = " + elevId + " WHERE ELEVHEMSNAMN = '" + elevhem + "'");

                        /* Om användaren klickar ur prefektstatus uppdateras prefektkolumnen med värdet null, OM eleven var prefekt före.
                         * prefektKontroll används så värdet inte blir null om användaren ändrar en icke-prefekts information.
                         */
                        } else if (prefektstatus == false && prefektKontroll != null) {
                            idb.update("UPDATE ELEVHEM SET PREFEKT = NULL WHERE ELEVHEMSNAMN = '" + elevhem + "'");
                        }

                        JOptionPane.showMessageDialog(null, "Ändrat!");
                    }
                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick fel!");
                System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }//GEN-LAST:event_btnAndraActionPerformed

    private void tomfalt() {
    // Tömmer fälten på information.
    
        txtElevId.setText(null);
        txtFornamn.setText(null);
        txtEfternamn.setText(null);
    }

    private void btnTillbakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTillbakaMouseClicked
        // Metoden stänger denna sida och går tillbaka till huvudsidan för admins.
        setVisible(false);
        Huvudsida_admin adminsidan = new Huvudsida_admin(idb);
        adminsidan.setVisible(true);
    }//GEN-LAST:event_btnTillbakaMouseClicked

    private void btnTomFaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomFaltActionPerformed
        // Metoden tömmer fälten på text om en klickar på "Töm fält" knappen.
        tomfalt();
        txtSok.setText("");
    }//GEN-LAST:event_btnTomFaltActionPerformed

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        // Tar fram information om eleven som användaren skriver in i sökfältet och sätter det i fälten på vänstersida.
        txtTips.setText(" ");

        try {
            // Skapar en Array där namnet delas in i substring förnamn och substring efternamn.
            String namnet = txtSok.getText();
            String[] fornamnefternamn = namnet.split(" ");
            int storlek = fornamnefternamn.length;

            /* Denna villkorssats behövs för annars fylls elevhemdropdown-menyn med kopior av elevhemmet vid varje sökning. Detta kollar
             * om dropdown-menyn är tom vid varje sökning (vilket den endast är vid första sökningen) och fyller på endast då.
             */
            if (cbElevhem.getItemCount() == 0) {
                fyllElevhemCombobox();
            }  
            
            // Dessa ser till att fältet inte är tomt eller att det finns mer än två namn (ett förnamn och ett efternamn).
            if (Validering.KollaTomtFalt(txtSok)) {
                if (Validering.KollaOmEttNamn(txtSok)) {

                    // Detta kolla om personen som användaren skrivit in namnet på finns i databasen.
                    String elevId = idb.fetchSingle("SELECT ELEV_ID FROM ELEV where FORNAMN='" + fornamnefternamn[0] + "' and    EFTERNAMN='" + fornamnefternamn[1] + "'");
                    if (Validering.KollaOmPersonFinns(elevId)) {

                        /* Villkoret kollar om både förnamn och efternamn har använts genom att kolla om ett mellanslag finns i sökfältet när
                         * värdet hämtas, och om det gör det så så kommer informationen skrivas ut om eleven ifråga hittas i databasen.
                         */
                        if (namnet.contains(" ") && storlek == 2) {

                            txtElevId.setText(elevId);
                            int elevIdInt = Integer.parseInt(elevId);

                            String fornamn = idb.fetchSingle("SELECT FORNAMN FROM ELEV where FORNAMN='" + fornamnefternamn[0] + "' and EFTERNAMN='" + fornamnefternamn[1] + "'");
                            txtFornamn.setText(fornamn);

                            String efternamn = idb.fetchSingle("SELECT EFTERNAMN FROM ELEV where FORNAMN='" + fornamnefternamn[0] + "' and EFTERNAMN='" + fornamnefternamn[1] + "'");
                            txtEfternamn.setText(efternamn);

                            
                            String elevhem = idb.fetchSingle("SELECT ELEVHEMSNAMN from ELEVHEM join SOVSAL on ELEVHEM.ELEVHEM_ID = SOVSAL.ELEVHEM join ELEV on ELEV.SOVSAL = SOVSAL_ID WHERE ELEV.FORNAMN='" + fornamnefternamn[0] + "' and EFTERNAMN='" + fornamnefternamn[1] + "'");
                            cbElevhem.setSelectedItem(elevhem);

                            // Tar bort innehåller i sovsal dropdown-menyn och fyller den pånytt med de aktuella sovsalarna utifrån elevhemmet eleven tillhör.
                            cbSovsal.removeAllItems();
                            ArrayList<HashMap<String, String>> sovsalLista = idb.fetchRows("SELECT SOVSAL_ID FROM SOVSAL JOIN ELEVHEM ON SOVSAL.ELEVHEM = ELEVHEM_ID WHERE ELEVHEMSNAMN = '" + elevhem + "'");

                            for (int i = 0; i < sovsalLista.size(); i++) {
                                cbSovsal.addItem(sovsalLista.get(i).get("SOVSAL_ID"));
                            }

                            String sovsal = idb.fetchSingle("SELECT SOVSAL FROM ELEV where FORNAMN='" + fornamnefternamn[0] + "' and EFTERNAMN='" + fornamnefternamn[1] + "'");
                            cbSovsal.setSelectedItem(sovsal);

                            // Kollar om eleven är prefekt eller inte genom at se om deras ID återfinns i prefektkolumnen.
                            String prefektStatus = idb.fetchSingle("SELECT ELEV_ID FROM ELEV JOIN SOVSAL ON ELEV.SOVSAL = SOVSAL_ID JOIN ELEVHEM ON ELEVHEM_ID = SOVSAL.ELEVHEM WHERE PREFEKT = " + elevIdInt);
                            if (prefektStatus == null) {
                                btnPrefekt.setSelected(false);
                            } else {
                                btnPrefekt.setSelected(true);
                            }
                        }
                    } else {
                        txtTips.setText("Kolla att du använder stora och små bokstäver på rätt ställen.");
                    }
                }
            }
            
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Sökningen gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }//GEN-LAST:event_btnSokActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // Metoden tar bort eleven användaren sökt fram från systemet.

        // Detta kollar om fältet med elevIDet är ifyllt, om det är tomt innebär det att det inte finns någon elev att ta bort.
        if (Validering.KollaTomtFalt(txtElevId)) {

            int elevId = Integer.parseInt(txtElevId.getText());

            // Tar bort eleven om användaren klickar i "YES" (värdet 0) i dialogrutan, annars händer ingenting.
            int input = JOptionPane.showConfirmDialog(null, "Är du säker på att du vill ta bort eleven?", "Ta bort elev..", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (input == 0) {
                try {
                    // Tar bort elevIDet från alla databastabeller den kanske är en främmande nyckel i före den till slut tar bort i elevtabellen.
                    idb.delete("DELETE FROM REGISTRERAD_PA WHERE ELEV_ID =" + elevId);
                    idb.delete("DELETE FROM HAR_BETYG_I WHERE ELEV_ID =" + elevId);
                    idb.update("UPDATE ELEVHEM SET PREFEKT = NULL WHERE PREFEKT =" + elevId);
                    idb.delete("DELETE FROM ELEV WHERE ELEV_ID =" + elevId);
                    JOptionPane.showMessageDialog(null, "Eleven har tagits bort!");
                    tomfalt();

                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Sökningen gick fel!");
                    System.out.println("Internt felmeddelande:" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void txtSokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSokMouseClicked
        // När man klickar på sökfältet töms det på text.
        txtSok.setText("");
    }//GEN-LAST:event_txtSokMouseClicked

    private void btnUppdateradListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateradListaActionPerformed
        // Anropar metoden som fyller på lsitan med alla elever på Hogwarts.
        fyllListan();
    }//GEN-LAST:event_btnUppdateradListaActionPerformed

    private void cbElevhemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbElevhemItemStateChanged
        // Metoden uppdaterar sovsaldropdown-menyn med de sovsalar som tillhör elevhemmet som väljs i elevhem-dropdownmenyn.

        cbSovsal.removeAllItems();
        String valtElevhem = cbElevhem.getSelectedItem().toString();

        try {
            int elevhemId = Integer.parseInt(idb.fetchSingle("SELECT ELEVHEM_ID FROM ELEVHEM WHERE ELEVHEMSNAMN = '" + valtElevhem + "'"));
            ArrayList<HashMap<String, String>> sovsalsLista = idb.fetchRows("SELECT SOVSAL_ID FROM SOVSAL WHERE ELEVHEM = " + elevhemId);

            for (int i = 0; i < sovsalsLista.size(); i++) {
                cbSovsal.addItem(sovsalsLista.get(i).get("SOVSAL_ID"));
            }

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Nått gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }//GEN-LAST:event_cbElevhemItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JRadioButton btnPrefekt;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JLabel btnTillbaka;
    private javax.swing.JButton btnTomFalt;
    private javax.swing.JButton btnUppdateradLista;
    private javax.swing.JComboBox<String> cbElevhem;
    private javax.swing.JComboBox<String> cbSovsal;
    private javax.swing.JTextArea elevLista;
    private javax.swing.JLabel iconElever;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbEfternamn;
    private javax.swing.JLabel lbElevId;
    private javax.swing.JLabel lbElevhem;
    private javax.swing.JLabel lbFornamn;
    private javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lbRubrik;
    private javax.swing.JLabel lbSovsal;
    private javax.swing.JLabel lbSubRubrik;
    private javax.swing.JLabel lbValjElev;
    private javax.swing.JPanel panelTitel;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtElevId;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtSok;
    private javax.swing.JLabel txtTips;
    // End of variables declaration//GEN-END:variables
}
