
import oru.inf.InfDB;

/*
 * Detta är huvudsidan för elever där de kan välja att använda de olika subsidorna som finns, eller logga ut.
 *
 * @author Elinore Hagman
 */
public class Huvudsida_elev extends javax.swing.JFrame {

private InfDB idb;
      
    // Creates new form Huvudsida_elev
    public Huvudsida_elev(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnElevinformation = new javax.swing.JPanel();
        lbElevinformation = new javax.swing.JLabel();
        iconHat = new javax.swing.JLabel();
        btnKursinformation = new javax.swing.JPanel();
        lbKursinformation = new javax.swing.JLabel();
        iconBook = new javax.swing.JLabel();
        btnBetyginformation = new javax.swing.JPanel();
        lbBetyginformation = new javax.swing.JLabel();
        iconBetyg = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        lbElevRubrik = new javax.swing.JLabel();
        btnElevhemspokal = new javax.swing.JPanel();
        lbElevhemspokal = new javax.swing.JLabel();
        iconPokal = new javax.swing.JLabel();
        iconEmblem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnElevinformation.setBackground(new java.awt.Color(204, 204, 204));
        btnElevinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnElevinformationMouseClicked(evt);
            }
        });

        lbElevinformation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbElevinformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbElevinformation.setText("Elevinformation");

        iconHat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconHat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8-graduate-filled-50.png"))); // NOI18N

        javax.swing.GroupLayout btnElevinformationLayout = new javax.swing.GroupLayout(btnElevinformation);
        btnElevinformation.setLayout(btnElevinformationLayout);
        btnElevinformationLayout.setHorizontalGroup(
            btnElevinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnElevinformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnElevinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbElevinformation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconHat, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnElevinformationLayout.setVerticalGroup(
            btnElevinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnElevinformationLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(iconHat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lbElevinformation)
                .addGap(15, 15, 15))
        );

        btnKursinformation.setBackground(new java.awt.Color(204, 204, 204));
        btnKursinformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKursinformationMouseClicked(evt);
            }
        });

        lbKursinformation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbKursinformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbKursinformation.setText("Kursinformation");

        iconBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8_literature_filled_50px.png"))); // NOI18N

        javax.swing.GroupLayout btnKursinformationLayout = new javax.swing.GroupLayout(btnKursinformation);
        btnKursinformation.setLayout(btnKursinformationLayout);
        btnKursinformationLayout.setHorizontalGroup(
            btnKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKursinformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbKursinformation, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(iconBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnKursinformationLayout.setVerticalGroup(
            btnKursinformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnKursinformationLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(iconBook)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lbKursinformation)
                .addGap(15, 15, 15))
        );

        btnBetyginformation.setBackground(new java.awt.Color(204, 204, 204));
        btnBetyginformation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBetyginformationMouseClicked(evt);
            }
        });

        lbBetyginformation.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbBetyginformation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbBetyginformation.setText("Betyginformation");

        iconBetyg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBetyg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8_report_card_filled_50px.png"))); // NOI18N

        javax.swing.GroupLayout btnBetyginformationLayout = new javax.swing.GroupLayout(btnBetyginformation);
        btnBetyginformation.setLayout(btnBetyginformationLayout);
        btnBetyginformationLayout.setHorizontalGroup(
            btnBetyginformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBetyginformationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnBetyginformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBetyginformation, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(iconBetyg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnBetyginformationLayout.setVerticalGroup(
            btnBetyginformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnBetyginformationLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(iconBetyg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(lbBetyginformation)
                .addGap(15, 15, 15))
        );

        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        lbElevRubrik.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lbElevRubrik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbElevRubrik.setText("VÄLKOMMEN ELEV");

        btnElevhemspokal.setBackground(new java.awt.Color(204, 204, 204));
        btnElevhemspokal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnElevhemspokalMouseClicked(evt);
            }
        });

        lbElevhemspokal.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbElevhemspokal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbElevhemspokal.setText("Elevhemspokalen");

        iconPokal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconPokal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/icons8_trophy_50px.png"))); // NOI18N

        javax.swing.GroupLayout btnElevhemspokalLayout = new javax.swing.GroupLayout(btnElevhemspokal);
        btnElevhemspokal.setLayout(btnElevhemspokalLayout);
        btnElevhemspokalLayout.setHorizontalGroup(
            btnElevhemspokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnElevhemspokalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnElevhemspokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbElevhemspokal, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(iconPokal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnElevhemspokalLayout.setVerticalGroup(
            btnElevhemspokalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnElevhemspokalLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(iconPokal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbElevhemspokal)
                .addGap(15, 15, 15))
        );

        iconEmblem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/crest_small.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(iconEmblem)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoggaUt)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnElevinformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBetyginformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnKursinformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbElevRubrik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnElevhemspokal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(lbElevRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconEmblem)))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnElevinformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnElevhemspokal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKursinformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBetyginformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnLoggaUt)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        // Loggar ut användaren och går tillbaka till inloggningsformuläret.
        setVisible(false);
        LoginWindow loginsidan = new LoginWindow(idb);
        loginsidan.setVisible(true);
    }//GEN-LAST:event_btnLoggaUtActionPerformed

    private void btnKursinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKursinformationMouseClicked
        // Stänger denna sida och öppnar sidan med kurser istället.
        setVisible(false);
        Kurser_elev kurserna = new Kurser_elev(idb);
        kurserna.setVisible(true);
    }//GEN-LAST:event_btnKursinformationMouseClicked

    private void btnElevinformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElevinformationMouseClicked
        // Stänger denna sida och öppnar sidan med elevinformation istället.
        setVisible(false);
        Elever_elev elevsidan = new Elever_elev(idb);
        elevsidan.setVisible(true);
    }//GEN-LAST:event_btnElevinformationMouseClicked

    private void btnBetyginformationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBetyginformationMouseClicked
        // Stänger denna sida och öppnar sidan med betyg istället.
        setVisible(false);
        Betyg_elev betygsidan = new Betyg_elev(idb);
        betygsidan.setVisible(true);
    }//GEN-LAST:event_btnBetyginformationMouseClicked

    private void btnElevhemspokalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnElevhemspokalMouseClicked
        // Stänger denna sida och öppnar sidan med elevhemspokalen istället.
        setVisible(false);
        Elevhemspokal_elev pokalen = new Elevhemspokal_elev(idb);
        pokalen.setVisible(true);
    }//GEN-LAST:event_btnElevhemspokalMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBetyginformation;
    private javax.swing.JPanel btnElevhemspokal;
    private javax.swing.JPanel btnElevinformation;
    private javax.swing.JPanel btnKursinformation;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JLabel iconBetyg;
    private javax.swing.JLabel iconBook;
    private javax.swing.JLabel iconEmblem;
    private javax.swing.JLabel iconHat;
    private javax.swing.JLabel iconPokal;
    private javax.swing.JLabel lbBetyginformation;
    private javax.swing.JLabel lbElevRubrik;
    private javax.swing.JLabel lbElevhemspokal;
    private javax.swing.JLabel lbElevinformation;
    private javax.swing.JLabel lbKursinformation;
    // End of variables declaration//GEN-END:variables
}
