
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * Detta är sidan som öppnas för användaren när programmet startas. Genom denna sida kan användaren
 * välja att fortsätta till elevsidan genom en knapp eller lärar- och adminsidan genom inloggningsformuläret.
 * För att logga in på lärar- eller adminsidan använder man sig av det unika LARAR_ID som finns i databasen som användarnamn. 
 *
 * @author Elinore Hagman
 */
public class LoginWindow extends javax.swing.JFrame {

    private InfDB idb;

    // Skapar ett nytt LoginWindow.
    public LoginWindow(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLarare = new javax.swing.JPanel();
        txtAnvandarnamn = new javax.swing.JTextField();
        lbAnvandarnamn = new javax.swing.JLabel();
        lbLosenord = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        txtLosenord = new javax.swing.JPasswordField();
        lbLarare = new javax.swing.JLabel();
        panelElev = new javax.swing.JPanel();
        lbElev = new javax.swing.JLabel();
        btnElevFortsatt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbHogwartsSymbol = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelLarare.setBackground(new java.awt.Color(204, 204, 204));
        panelLarare.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelLarare.setPreferredSize(new java.awt.Dimension(300, 150));

        lbAnvandarnamn.setText("Användarnamn:");

        lbLosenord.setText("Lösenord:");

        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        lbLarare.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbLarare.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLarare.setText("Är du lärare?");

        javax.swing.GroupLayout panelLarareLayout = new javax.swing.GroupLayout(panelLarare);
        panelLarare.setLayout(panelLarareLayout);
        panelLarareLayout.setHorizontalGroup(
            panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbLarare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLarareLayout.createSequentialGroup()
                .addGroup(panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLoggaIn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLarareLayout.createSequentialGroup()
                        .addGroup(panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLarareLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbAnvandarnamn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLarareLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lbLosenord)))
                        .addGap(18, 18, 18)
                        .addGroup(panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLosenord)
                            .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelLarareLayout.setVerticalGroup(
            panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLarareLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbLarare)
                .addGap(31, 31, 31)
                .addGroup(panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAnvandarnamn))
                .addGap(18, 18, 18)
                .addGroup(panelLarareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLosenord)
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoggaIn)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelElev.setBackground(new java.awt.Color(204, 204, 204));
        panelElev.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        panelElev.setPreferredSize(new java.awt.Dimension(300, 150));

        lbElev.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbElev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbElev.setText("Är du elev?");

        btnElevFortsatt.setText("Fortsätt som elev");
        btnElevFortsatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElevFortsattActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 2, 13)); // NOI18N
        jLabel1.setText("Även lärare kan kolla allmän information här");

        javax.swing.GroupLayout panelElevLayout = new javax.swing.GroupLayout(panelElev);
        panelElev.setLayout(panelElevLayout);
        panelElevLayout.setHorizontalGroup(
            panelElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelElevLayout.createSequentialGroup()
                .addGroup(panelElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelElevLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnElevFortsatt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelElevLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbElev, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelElevLayout.setVerticalGroup(
            panelElevLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelElevLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbElev)
                .addGap(56, 56, 56)
                .addComponent(btnElevFortsatt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lbHogwartsSymbol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bilder/hogwarts_logo.png"))); // NOI18N
        lbHogwartsSymbol.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(panelLarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelElev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lbHogwartsSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbHogwartsSymbol, javax.swing.GroupLayout.PREFERRED_SIZE, 255, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLarare, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(panelElev, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnElevFortsattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElevFortsattActionPerformed
    // Denna metod vidarebefodrar en till huvudsidan för elever och stänger loginsidan.
        setVisible(false);
        Huvudsida_elev elevsidan = new Huvudsida_elev(idb);
        elevsidan.setVisible(true);
    }//GEN-LAST:event_btnElevFortsattActionPerformed

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
    // Denna metod vidarebefodrar en till huvudsidan antingen för admins eller vanliga lärare beroende på ens behörighet.
    
        String anvandarinput = txtAnvandarnamn.getText();
        String loseninput = txtLosenord.getText();

        // Dessa ser till att samtliga textfält inte är tomma och att användarnamnet endast tar emot siffror.
        if (Validering.Kolla2TommaFalt(txtAnvandarnamn, txtLosenord)) {
            if (Validering.KollaFaltEfterSiffror(txtAnvandarnamn)) {

                try {
                    String anvandarnamnet = idb.fetchSingle("select LARAR_ID from LARARE where LARAR_ID =" + anvandarinput);
                    String losenordet = idb.fetchSingle("select LOSENORD from LARARE where LARAR_ID =" + anvandarinput);
                    String adminstatus = idb.fetchSingle("select ADMINISTRATOR from LARARE where LARAR_ID=" + anvandarinput);

                    // Denna villkorssats kollar om lösenordet stämmer överens med användarnamnet, och om användaren INTE är admin.
                    if (anvandarinput.equals(anvandarnamnet) && loseninput.equals(losenordet) && adminstatus.equals("F")) {
                        setVisible(false);
                        Huvudsida_larare lararsidan = new Huvudsida_larare(idb);
                        lararsidan.setVisible(true);

                    // Denna villkorssats kollar om lösenordet stämmer överens med användarnamnet, och om användaren ÄR admin.
                    } else if (anvandarinput.equals(anvandarnamnet) && loseninput.equals(losenordet) && adminstatus.equals("T")) {
                        setVisible(false);
                        Huvudsida_admin adminsidan = new Huvudsida_admin(idb);
                        adminsidan.setVisible(true);

                    // Denna händelse sker om lösenordet inte stämmer överens med användarnamnet som skrivits in.  
                    } else {
                        JOptionPane.showMessageDialog(null, "Kunde inte hitta användare!\nKom ihåg att lösenordet är skiftlägeskänsligt!");
                    }

                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Ett fel uppstod.");
                    System.out.println("Internt felmeddelande:" + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnLoggaInActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElevFortsatt;
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbAnvandarnamn;
    private javax.swing.JLabel lbElev;
    private javax.swing.JLabel lbHogwartsSymbol;
    private javax.swing.JLabel lbLarare;
    private javax.swing.JLabel lbLosenord;
    private javax.swing.JPanel panelElev;
    private javax.swing.JPanel panelLarare;
    private javax.swing.JTextField txtAnvandarnamn;
    private javax.swing.JPasswordField txtLosenord;
    // End of variables declaration//GEN-END:variables
}
